/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "on-secondary-container": "#003567",
        "surface-bright": "#f9f9ff",
        "surface-container-high": "#dee8ff",
        "on-primary-fixed": "#002111",
        "error-container": "#ffdad6",
        "surface-variant": "#d8e3fb",
        "outline-variant": "#becabf",
        "on-tertiary": "#ffffff",
        "on-error-container": "#93000a",
        "tertiary": "#b5004c",
        "outline": "#6e7a71",
        "inverse-primary": "#7adaa3",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed": "#3f0016",
        "on-primary-container": "#ebffef",
        "surface-container-highest": "#d8e3fb",
        "primary-fixed": "#96f6bd",
        "inverse-on-surface": "#ecf1ff",
        "error": "#ba1a1a",
        "on-surface-variant": "#3e4941",
        "surface-dim": "#cfdaf2",
        "tertiary-container": "#dc1f63",
        "tertiary-fixed-dim": "#ffb2bf",
        "on-background": "#111c2d",
        "surface-container-low": "#f0f3ff",
        "on-tertiary-fixed-variant": "#90003b",
        "primary-fixed-dim": "#7adaa3",
        "surface-tint": "#006d42",
        "surface-container-lowest": "#ffffff",
        "on-error": "#ffffff",
        "inverse-surface": "#263143",
        "secondary": "#005faf",
        "on-primary": "#ffffff",
        "on-tertiary-container": "#fff8f8",
        "on-primary-fixed-variant": "#005231",
        "secondary-fixed-dim": "#a5c8ff",
        "on-surface": "#111c2d",
        "primary": "#006840",
        "on-secondary-fixed": "#001c3a",
        "on-secondary-fixed-variant": "#004786",
        "secondary-container": "#54a0fe",
        "tertiary-fixed": "#ffd9de",
        "surface": "#f9f9ff",
        "surface-container": "#e7eeff",
        "background": "#f9f9ff",
        "primary-container": "#1b8354",
        "secondary-fixed": "#d4e3ff"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "space-sm": "0.75rem",
        "space-lg": "1.75rem",
        "space-xs": "0.375rem",
        "space-xl": "2.5rem",
        "gutter": "1rem",
        "gutter-mobile": "0.75rem",
        "space-md": "1.25rem",
        "margin-mobile": "1rem",
        "margin": "1.5rem"
      },
      "fontFamily": {
        "headline-xl-mobile": ["Noto Sans"],
        "headline-lg": ["Noto Sans"],
        "headline-xl": ["Noto Sans"],
        "headline-md": ["Noto Sans"],
        "audio-banner": ["Noto Sans"],
        "label-md": ["Noto Sans"],
        "body-xl": ["Noto Sans"],
        "label-lg": ["Noto Sans"],
        "headline-lg-mobile": ["Noto Sans"],
        "body-md": ["Noto Sans"],
        "body-lg": ["Noto Sans"]
      },
      "fontSize": {
        "headline-xl-mobile": ["26px", {"lineHeight": "36px", "fontWeight": "700"}],
        "headline-lg": ["24px", {"lineHeight": "34px", "fontWeight": "700"}],
        "headline-xl": ["32px", {"lineHeight": "44px", "fontWeight": "700"}],
        "headline-md": ["20px", {"lineHeight": "30px", "fontWeight": "600"}],
        "audio-banner": ["18px", {"lineHeight": "26px", "fontWeight": "700"}],
        "label-md": ["14px", {"lineHeight": "20px", "fontWeight": "600"}],
        "body-xl": ["19px", {"lineHeight": "30px", "fontWeight": "500"}],
        "label-lg": ["16px", {"lineHeight": "22px", "fontWeight": "600"}],
        "headline-lg-mobile": ["22px", {"lineHeight": "32px", "fontWeight": "700"}],
        "body-md": ["15px", {"lineHeight": "24px", "fontWeight": "400"}],
        "body-lg": ["17px", {"lineHeight": "28px", "fontWeight": "400"}]
      }
    }
  },
  plugins: [],
}
